//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeviceDetails
    {
        public int id { get; set; }
        public string location { get; set; }
        public string type { get; set; }
        public string device_health { get; set; }
        public Nullable<System.DateTime> last_used { get; set; }
        public Nullable<decimal> price { get; set; }
        public string color { get; set; }
    }
}
